### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by Mayank8080**

### CODE REVIEW

**Comment by miguno** [comment]
This PR has a few issues, so I am closing it.

- The current `pom.xml` already uses `maven.compiler.release`, which is better than using the `source` and `target` options. From the maven documentation about the aforementioned setting:

> This means that, unlike the [-source` and -target options](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html), the compiler will detect and generate an error when using APIs that don't exist in previous releases of Java SE. ([source](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html))

- The PR duplicates the source encoding setting, which already exists in `pom.xml`.

**Comment by miguno** [comment]
Also, a general piece of feedback for @Mayank8080: I strongly suggest to always provide a description for any PRs you create on GitHub.  It is considered bad manner to create PRs without any information on the PR’s purpose and why you think the PR should be merged.

**Comment by Mayank8080** [comment]
Sorry for that

**Comment by Mayank8080** [comment]
Thanks for the feedback

**Pull request closed without merging**
